name: Backend CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Test with maven
        working-directory: 'backend'
        run: mvn verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_SECRET }}
          working-directory: 'backend'
          directory: ./coverage/reports/
          env_vars: OS
          fail_ci_if_error: true
          files: /home/runner/work/commission/commission/backend/target/site/jacoco/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: 'backend'
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'commission-backend'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
